# Generated by Django 5.1.2 on 2024-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenZoneSpaces', models.IntegerField(default=66)),
                ('blueZoneSpaces', models.IntegerField(default=66)),
                ('redZoneSpaces', models.IntegerField(default=66)),
            ],
        ),
    ]
