# Generated by Django 5.1.2 on 2024-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parkingName',
            field=models.CharField(default='defaultParking', max_length=50),
        ),
    ]
