# Generated by Django 5.1.2 on 2024-10-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_parkingname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parkingName',
            new_name='name',
        ),
    ]
