# Generated by Django 5.1.2 on 2024-10-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_parking_bluezonespaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='zone',
        ),
        migrations.AddField(
            model_name='parking',
            name='blueZoneSpaces',
            field=models.IntegerField(default=66),
        ),
        migrations.AddField(
            model_name='parking',
            name='greenZoneSpaces',
            field=models.IntegerField(default=66),
        ),
        migrations.AddField(
            model_name='parking',
            name='redZoneSpaces',
            field=models.IntegerField(default=66),
        ),
    ]
