# Generated by Django 5.1.3 on 2024-11-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('access_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_access.vehicle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_access.zone')),
            ],
        ),
    ]
