# Generated by Django 5.1.3 on 2024-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleaccess',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicleaccess',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleAccess',
        ),
    ]
