# Generated by Django 5.1.2 on 2024-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entryTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exitTime',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
    ]
