# Generated by Django 5.1.2 on 2024-10-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_parkingname_parking_name'),
        ('transactions', '0004_rename_entrytime_transaction_transactiontimestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parking.parking'),
            preserve_default=False,
        ),
    ]
