# Generated by Django 5.1.2 on 2024-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='zone',
            field=models.CharField(choices=[('greenZone', 'Green Zone'), ('blueZone', 'Blue Zone'), ('redZone', 'Red Zone')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
