# Generated by Django 5.1.3 on 2024-11-14 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
