# Generated by Django 5.1.2 on 2024-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=40)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
            ],
        ),
    ]
